name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get install libsdl2-dev
    - name: configure
      run: cmake -G "Unix Makefiles" -B ./build/
    - name: make
      run: cmake --build ./build/ --clean-first
